name: Deploy to GCS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          
      - name: Deploy to Google Cloud Storage
        run: |
          gsutil -m rsync -r . gs://${{ secrets.GCS_BUCKET_NAME }} -x ".git/|.github/|.gitignore|CLAUDE.md"
          
      - name: Set CORS policy
        run: |
          gsutil cors set cors.json gs://${{ secrets.GCS_BUCKET_NAME }}