name: Deploy to GCS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      id-token: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/411022031947/locations/global/workloadIdentityPools/dev-workflows-pool/providers/github-workflows
          service_account: broken-web-github-deployer@broken-dev.iam.gserviceaccount.com
          create_credentials_file: true

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          
      # Step 1: Deploy all files from public directory
      - name: Deploy public directory to Google Cloud Storage
        run: |
          echo "Deploying public directory to broken.dev"
          gsutil -m rsync -r public/ gs://broken.dev/
          echo "Listing bucket contents:"
          gsutil ls gs://broken.dev/
          
      # Step 2: Apply GCS bucket configurations
      - name: Configure GCS bucket
        run: |
          # Set CORS policy
          echo "Setting CORS policy"
          gsutil cors set config/cors.json gs://broken.dev
          
          # Set website configuration
          echo "Setting website configuration"
          gsutil web set -m index.html -e 404.html gs://broken.dev
          
          # Set public access
          echo "Setting public access"
          gsutil iam ch allUsers:objectViewer gs://broken.dev
          
          # Verify configuration
          echo "Verifying website configuration"
          gsutil web get gs://broken.dev